# Generated by Django 4.2.7 on 2023-11-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complate',
            new_name='complete',
        ),
    ]
